sudo: false

language: node_js
node_js:
  - 12

notifications:
  webhooks: https://coveralls.io/webhook
  
script:
  - npm run typecheck
  - npm run lint
  - npm run build
  - npm run test
  - npm run coverage
  - npm run coveralls